name: Check repository on pull_request

on:
  pull_request:
    branches:
      - "**"

jobs:
  check-repository:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Check Linters && format
        run: |
          npm run lint
          npm run check-format

      - name: Run tests
        run: npm run test

      # - name: Run e2e tests
      #   run: npm run test:e2e

      - name: Say good bye
        run: echo "Hasta aca todo bien"
